In [1]:
import numpy as np

In [4]:
#1
#tablica zawierająca 10 zer
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#2
#tablica zawierająca 10 piątek
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [8]:
#3
#tablica zawierająca liczby od 10 do 50
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [12]:
#4
#macierz o wymiarach 3x3 zawierającą liczby od 0 do 8
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
#5
#macierz jednostkowa o wymiarach 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
#6
#macierz o wymiarach 5x5 zawierającą liczby z dystrybucji normalnej (Gaussa)
np.random.normal(0,1,25).reshape(5,5)

array([[ 1.73695292,  2.03021572, -0.40192175,  1.289607  ,  0.39144417],
       [ 0.18387729,  0.37193184, -0.41589107,  0.34435979,  0.18099714],
       [-0.48468965, -1.59732712,  1.56519951, -1.62343165,  0.01644732],
       [-0.40586116, -1.30961063,  0.79001197, -1.27739438, -0.54019986],
       [-0.5783538 ,  1.76348954, -0.76463507,  0.73508798,  0.20248611]])

In [30]:
#7
#macierz o wymiarach 10x10 zawierającą liczby od 0,01 do 1 z krokiem 0,01
np.arange(0.01, 1.01, 0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [34]:
#8
#tablica zawierająca 20 liniowo rozłożonych liczb między 0 a 1 (włącznie z 0 i 1)
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [86]:
#9
#tablica zawierająca losowe liczby z przedziału (1, 25), następnie zamień ją na macierz o wymiarach 5 x 5 z tymi samymi liczbami
task9=np.random.random((5,5))*25
#task9.reshape(5,5)
task9

array([[ 6.81830888, 21.42269957, 10.85834213,  2.0110324 ,  5.7107399 ],
       [24.43258007, 13.80092105,  8.63307358, 18.61684554,  7.23770702],
       [21.02822286, 15.48543084,  8.62268352, 11.59659742,  9.60352398],
       [20.18653337,  3.79265931,  5.1130419 , 19.05495468, 17.76555406],
       [22.40363892, 21.41928593, 14.93680279, 14.32698019, 14.47496671]])

In [74]:
#9 A
#suma wszystkich liczb w ww. macierzy,
task9.sum()

310.96053773117967

In [73]:
#9 B
#średnia wszystkich liczb w ww. macierzy,
task9.mean()

12.438421509247187

In [75]:
#9 C
#standardowa dewiacja dla liczb w ww. macierzy
task9.std()

7.048530010574018

In [88]:
#9 D
#suma każdej kolumny ww. macierzy
task9.sum(axis=1)

array([46.82112287, 72.72112725, 66.33645862, 65.91274332, 87.56167454])

In [90]:
#10
#macierz o wymiarach 5x5 zawierającą losowe liczby z przedziału (0, 100)
task10=np.random.random((5,5))*100
task10

array([[ 3.69070157, 33.19908349, 27.33033523, 21.41072247, 23.44122579],
       [99.64100023, 26.50492087, 49.75548005, 50.0904238 , 53.48602529],
       [45.78343491,  9.41022397, 86.39993328, 89.67381877, 98.4283406 ],
       [39.55592937, 35.4008253 , 57.15052269, 65.43113908, 49.89012301],
       [59.19612112,  5.83213972, 26.14168479, 80.93748531, 34.65240578]])

In [92]:
#10 A
#mediana tych liczb
np.median(task10)

45.78343491245261

In [93]:
#10 B
#najmniejsza liczba tej macierzy
task10.min()

3.6907015717440705

In [94]:
#10 C
#największa liczba tej macierzy
task10.max()

99.6410002276924

In [99]:
#11
#macierz o wymiarach różnych od siebie i większych od 1, 
#zawierającą losowe liczby z przedziału (0, 100)
task11=np.random.random((3,6))*100
task11

array([[68.75011364, 55.5624032 ,  4.81445504, 27.02849325, 20.20716356,
        76.34802185],
       [18.11096538, 76.29600519, 39.89516495, 56.77936541, 73.16144118,
        86.89442378],
       [86.79761432, 99.05352429, 71.70964147, 53.32218963, 88.99336089,
        82.04300523]])

In [100]:
#11 A
# transpozycja tej macierzy
task11.transpose() 

array([[68.75011364, 18.11096538, 86.79761432],
       [55.5624032 , 76.29600519, 99.05352429],
       [ 4.81445504, 39.89516495, 71.70964147],
       [27.02849325, 56.77936541, 53.32218963],
       [20.20716356, 73.16144118, 88.99336089],
       [76.34802185, 86.89442378, 82.04300523]])

In [110]:
#12
#dwie macierze o odpowiednich wymiarach większych od 2
matr1=np.arange(4) 
matr2=np.arange(20).reshape(5,4)
print(matr1,'\n', matr2)

[0 1 2 3] 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [111]:
#Dodanie macierzy
print(np.add(matr1, matr2))

[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]
 [16 18 20 22]]


In [112]:
#13 
#Pomnożenie macierzy przy pomocy multiply
np.multiply(matr1, matr2)

array([[ 0,  1,  4,  9],
       [ 0,  5, 12, 21],
       [ 0,  9, 20, 33],
       [ 0, 13, 28, 45],
       [ 0, 17, 36, 57]])

In [127]:
#13 A
#pomnożenie macierzy przy pomocy matmul
matr3=np.arange(12).reshape(3,4)
matr4=np.arange(12).reshape(4,3)
print(matr3,'\n \n', matr4)
np.matmul(matr3, matr4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [ ]:
#14 Dodatkowe zadanie
#krótko opisać i uruchomić wszystkie funkcje (od ‘add’ do ‘lcm’) z sekcji ‘Math operations’ 

In [128]:
#14.1
#add - dodaje argumenty
np.add(2,5)

7

In [130]:
#14.2
#subtract - odejmuje argumenty
np.subtract(4,12)

-8

In [131]:
#14.3
#multiply - mnoży argumenty
np.multiply(7,5)

35

In [132]:
#14.4
#divide - dzieli argumenty
np.divide(8,4)

2.0

In [133]:
#14.5.1
#logaddexp - służy do obliczania logarytmu sumy potęgowań
arr1=[2,4,6]
arr2=[4,1,5]
np.logaddexp(arr1, arr2)

array([4.12692801, 4.04858735, 6.31326169])

In [136]:
#14.5.2
#drugi sposób wykorzystania
a=np.log(4.2e-60)
b=np.log(6.8e-40)
np.logaddexp(a,b)

-90.18648110757977

In [137]:
#14.6
#logaddexp2 - służy do obliczania logarytmu sumy potęgowań danych wejściowych, przydatna w uczeniu maszynowym
np.logaddexp2(arr1,arr2)

array([4.32192809, 4.169925  , 6.5849625 ])

In [141]:
#14.7
#true_divide - zwraca prawdziwy podział danych wejściowych, pod względem elementów.
c=np.arange(6)
np.true_divide(c,5)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [144]:
#14.8
#floor_divide- zwraca największą liczbę całkowitą mnniejszą bądź równą wynikowi dzielenia. (zaokrąglenie "do dołu" po dzieleniu)
np.floor_divide(13,3)

4

In [145]:
#14.9
#negative - neguje podane liczby
np.negative([13.,-57.])

array([-13.,  57.])

In [148]:
#14.10
#positive - odpowiednik x.copy(), zdefiniowany tylko dla typów obsługujących arytmetykę
d=[13, -57, -9, -111]
np.positive(d)

array([  13,  -57,   -9, -111])

In [153]:
#14.11
#power - podnosi tablicę do potęgi podanej w wyrażeniu
e=np.arange(5)
print(e)
np.power(e,3)

[0 1 2 3 4]


array([ 0,  1,  8, 27, 64], dtype=int32)

In [155]:
#14.12
#remainder - zwraca resztę z dzielenia elementów tablic
np.remainder([3, 11], [2, 3])

array([1, 2], dtype=int32)

In [158]:
#14.13
#mod - tak samo jak funkcja remainder zwraca resztę z dzielenia elementów tablic
np.mod([3, 11], [2, 3])

array([1, 2], dtype=int32)

In [160]:
#14.14
#fmod - działa bardzo podobnie jak funkcje wyżej, uwzględnia też znak minus (-)
np.fmod([-3, -2, -1, 1, 2, 3, 4], 3)

array([ 0, -2, -1,  1,  2,  0,  1], dtype=int32)

In [164]:
#14.15
#divmod - zwraca jednocześnie resztę z dzielenia oraz iloraz elementarny
np.divmod(np.arange(5), 3)

(array([0, 0, 0, 1, 1], dtype=int32), array([0, 1, 2, 0, 1], dtype=int32))

In [166]:
#14.16
#absolute - oblicza wartość bezwzgledną tablicy
f = [-7, 1, -13, -88]
np.absolute(f)

array([ 7,  1, 13, 88])

In [168]:
#14.17
#fabs - oblicza wartość bezwzględną podanej liczby
np.fabs(-7)

7.0

In [170]:
#14.18
#rint - zaokrągla elementy tablicy do najbliższej liczby całkowitej
g=np.array([-1.9, -1.5, -0.2, 0.7, 1.5, 1.7, 2.6])
np.rint(g)

array([-2., -2., -0.,  1.,  2.,  2.,  3.])

In [173]:
#14.19
#sign - zwraca oznaczenie podanych liczb (dodatnia czy ujemna)
np.sign([-5., 4.5, 17, -81])

array([-1.,  1.,  1., -1.])

In [188]:
#14.20
#heaviside - oblicza wyrażenie, którego funkcja jest poniżej:
#                                                0   if x1 < 0
#                          heaviside(x1, x2) =  x2   if x1 == 0
#                                                1   if x1 > 0
np.heaviside([1.5, -7, 2.0], 1)

array([1., 0., 1.])

In [191]:
#14.21
#conjugate - zwraca koniugat złożony. Złożony koniugat liczby zespolonej uzyskuje się poprzez zmianę znaku jego części urojonej.
h = np.eye(3) + 1j * np.eye(3)
np.conjugate(h)

array([[1.-1.j, 0.-0.j, 0.-0.j],
       [0.-0.j, 1.-1.j, 0.-0.j],
       [0.-0.j, 0.-0.j, 1.-1.j]])

In [ ]:
#14.22
#conj - jest tym samym co funkcja conjugate powyżej

In [200]:
#14.23
#exp - oblicza e^x dla każdej wartości x w tablicy wejściowej.
np.exp(np.arange(10))

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [205]:
#14.24
#exp2 - podnosi cyfrę 2 do potęg wskazanych w tablicy
np.exp2([3, 5])

array([ 8., 32.])

In [213]:
#14.25
#log - logarytm naturalny
np.log([1, 33, np.e, 12])

array([0.        , 3.49650756, 1.        , 2.48490665])

In [215]:
#14.26
#log2 - logarytm o podstawie 2
i = np.array([33, 1, 2, np.e])
np.log2(i)

array([5.04439412, 0.        , 1.        , 1.44269504])

In [217]:
#14.27
#log10 - logarytm dziesiętny
np.log10([1e-15, 3, np.e])

array([-15.        ,   0.47712125,   0.43429448])

In [219]:
#14.28
#expm1 - oblicza exp(x)-1 dla wszystkich elementów w tablicy.
np.expm1(1e-11)

1.000000000005e-11

In [222]:
#14.29
#log1p - zwraca logarytm naturalny z 1 plus tablicę wejściową
np.log1p(4e-59)

4e-59

In [226]:
#14.30
#sqrt - zwraca pierwiastek danej liczby
np.sqrt([1,35, 81, 145])

array([ 1.        ,  5.91607978,  9.        , 12.04159458])

In [233]:
#14.31
#square - zwraca elementy tablicy podniesione do potęgi 2
np.square([31, 12])

array([961, 144], dtype=int32)

In [235]:
#14.32
#cbrt - zwraca pierwiastek 3 stopnia elementów tablicy
np.cbrt([1,8,64, 563])

array([1.        , 2.        , 4.        , 8.25726327])

In [238]:
#14.33
#reciprocal - zwraca odwrotność argumentów (wyrażenie 1/x )
np.reciprocal([2, 7., 3.33])

array([0.5       , 0.14285714, 0.3003003 ])

In [248]:
#14.34
#gcd - zwraca największy wspólny dzielnik podanych liczb
np.gcd(125, 60)

5

In [253]:
#14.35
#lcm - zwraca najniższą wspólną wielokrotność podanych liczb
np.lcm(12, 20)

60